frontend: rest
server:
  address: 0.0.0.0
  port: 8087
  timeout:
    idle: 60
    read: 15
    write: 15
database:
  use: postgres
  postgres:
    url: todo
    port: 5432
    user: posgtres
    password: postgres
  mysql:
    url: todo
    db: testdb
    port: 3309
    user: user
    password: password
