server:
  address: 0.0.0.0
  port: 8087
  timeout:
    idle: 60
    read: 35
    write: 35
database:
  postgres:
    host: localhost
    dbname: postgres
    port: 5432
    user: postgres
    sslmode: disable
    max:
      attempts: 5
